#!/usr/bin/env bash

readonly pathToRbenv="$(which rbenv || echo "")"
if [[ -z "${pathToRbenv}" ]]; then
  echo "cannot run ruby because no rbenv installed" > /dev/stderr
  exit 1
elif [[ ! -x "${pathToRbenv}" ]]; then
  echo "cannot run ruby because rbenv[${pathToRbenv}] is not executable" > /dev/stderr
  exit 1
fi

function fail() {
    echo "FAILURE!!" > /dev/stderr
    exit 4
}

"${pathToRbenv}" exec "${@}" || fail
