name: Ruby

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - id: chrome
        name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120

      - run: ${{ steps.chrome.outputs.chrome-path }} "--version"
        name: Show Chrome Version

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec cucumber
